[package]
name = "syslog_rfc5424"
version = "0.4.0"
authors = ["James Brown <roguelazer@roguelazer.com>"]
description = "Parser for RFC5424 (IETF-format) syslog messages"
documentation = "http://roguelazer.github.io/rust-syslog-rfc5424/syslog_rfc5424/"
homepage = "https://github.com/Roguelazer/rust-syslog-rfc5424"
repository = "https://github.com/Roguelazer/rust-syslog-rfc5424"
license = "ISC"
readme = "README.md"

[dependencies]
# this should be a dev dependency, but there's some kind of issue with
# dev-only macro crates
assert_matches = "1.0"
chrono = "0.4.0"

[dev-dependencies]
timeit = "0.1"
